-- AlterTable
ALTER TABLE "ApiKey" ADD COLUMN "promptTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ApiKey" ADD COLUMN "completionTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ApiKey" ADD COLUMN "totalTokens" INTEGER NOT NULL DEFAULT 0;
